defaults: &default
  text: 'Pending'
  icon: 'slides'
  tags: []
  # href: 'video link'
  # view: 'slide link'
  # time: '00:00'
  # save: '/files/????.pdf'

course_intro:
  <<: *default
  text: 'Course Introduction'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vS8sACyf9lrjGUTkS3TxSuq0v6As8POig4tSvkYseWYTaHtpYb9JEaFz8CWI6M2hNVJB8kEUQHHMaW5/pub?start=false&loop=false&delayms=3000'
  save: '/files/Course Introduction.pdf'

projects:
  <<: *default
  text: 'Project Overview'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vS6DlWNE2SBOL_7TRoKEsIq9LwLhZXJvkTAxkO5drcCfSA80pnWt_jnOEQ3-nVqLW-L-S179iykHOj9/pub?start=false&loop=false&delayms=3000'
  save: '/files/Project Overview.pdf'

exceptions:
  <<: *default
  text: 'Exception Handling'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fc1367c9-aa48-4e6d-82bf-afaf015097f9'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRMqQrt0IaiwZL5Du1KcQIONLkNXtnS6VR2FnRXBn1c84dMSleUuH6jl0OJNLtSMS_WujxCSow9UXcI/pub?start=false&loop=false&delayms=3000'
  save: '/files/Exception Handling.pdf'
  time: '10:25'
  tags: ['exceptions']

paths:
  <<: *default
  text: 'Paths and Files'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=825bbf06-997d-438e-b712-afaf015099a0'
  time: '20:29'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRjEUU0FIhBZIeMeU9O5L3Fc9WFAb9RvjA3dNANUjxupwWPH6Uw86tYEczVtrbfDzLFLub3je-pwGsg/pub?start=false&loop=false&delayms=3000'
  save: '/files/Paths and Files.pdf'
  tags: ['files']

data:
  <<: *default
  tags: ['data']
  text: 'Abstract Data Types'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d4aa37cf-3337-4b1e-bd70-afaf015097d3'
  time: '12:25'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTkWFYYWCAs5DHir-jf68Yd5BWa_u8ymf7Ez-gqRaAhgmzEbyI0WoThN9tWPoa7EzgrkJDyaI65vZL3/pub?start=false&loop=false&delayms=3000'
  save: '/files/Abstract Data Types.pdf'

framework:
  <<: *default
  tags: ['data']
  text: 'Collections Framework'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=982b0640-d13b-48ce-8493-afaf01509713'
  time: '20:26'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQ3tDfuttbeApPhgaOhsyxjHrUeIMub206X9HWbs2cORCCGD1b2o05jDBhtNPeK_GxuhsfSLM_RcLDT/pub?start=false&loop=false&delayms=3000'
  save: '/files/Collections Framework.pdf'

help:
  <<: *default
  tags: ['none']
  text: 'Getting Help'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vSxGLWZBMDIPj7uV_8tB7Y2l9cgAoygX5dO9ip5vD3d_MdoSepNW7x2rRg7rmuR6G2O1eKCnVQrb6Xs/pub?start=false&loop=false&delayms=3000'
  save: '/files/Getting Help.pdf'

oop:
  <<: *default
  tags: ['objects']
  text: 'Object Oriented Programming'
  time: '25:22'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=47838700-2052-4e68-b6f7-afa2012c87e3'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQkzEnVG9sFgjElR-K2xUi91wYtj3bC82mWk8XhaRaz3ihMJNqQbciSKSkAxJAw_UQW7TGo-Cevsp05/pub?start=false&loop=false&delayms=3000'
  save: '/files/Object Oriented Programming.pdf'

generics:
  <<: *default
  tags: ['inheritance']
  text: 'Generic Types'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8f3be91f-6e33-4838-ae40-afa5012f761c'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRczaRucL8_HpFU1hH8WY7TQr2XSplEUY78sBK9t-hTCIkDK9kDvAuVne569IHct2tDNG9724VeE92g/pub?start=false&loop=false&delayms=3000'
  save: '/files/Generic Types.pdf'
  time: '16:53'

inheritance:
  <<: *default
  tags: ['inheritance']
  text: 'Inheritance Relationships'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8dafbf27-1c7d-4a7c-aa2f-afa5013a6828'
  time: '15:09'
  save: '/files/Inheritance Relationships.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQLIWhawaa54n5rjvtPsfTb4WyrQ_TdGUobkSssetDUpRopHK43W5P16lic_0aerDoWtentZhhshsGJ/pub?start=false&loop=false&delayms=3000'

abstract:
  <<: *default
  tags: ['inheritance']
  text: 'Abstract and Interfaces'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=217a9f63-2bcd-4869-b79c-afa5013a66f5'
  time: '14:36'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRARVHCO1k8XhC-yjANvl89WX91qKPJ9e3f2Em8ITBihWDf0Xym01x38Bz8DdigBFHHMfrgtuwgCFGE/pub?start=false&loop=false&delayms=3000'
  save: '/files/Abstract and Interfaces.pdf'

final:
  <<: *default
  tags: ['inheritance']
  text: 'Final Keyword'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4e843b8f-0703-4199-ba76-afa5013a67b1'
  time: '10:06'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQ1ZQfSwdQPikCJFXVf5YbWHAMh95r84nAr5Ply5DeYYY0OqU0EqJA0wsSFiX49Eh9qjyZhsFkGNZzs/pub?start=false&loop=false&delayms=3000'
  save: '/files/Final Keyword.pdf'

casting:
  <<: *default
  tags: ['inheritance']
  text: 'Casting'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4eab4121-1dad-40c5-a5a1-afa5013a671f'
  time: '10:42'
  save: '/files/Casting.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQKZWkx3KuWfriEUZx8n3VWwWJwqq1MyiMoJwWqXPQ-B8HdsaaOZgMPQ3cwDhuBcahLrDz3jtNKoeH-/pub?start=false&loop=false&delayms=3000'

object:
  <<: *default
  tags: ['inheritance', 'objects']
  text: 'Object Class'
  save: '/files/Object Class.pdf'
  time: '06:59'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8c2e483d-a4a3-4691-b8b1-afa201317dd4'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQgaY1m74u6_3ra6dibqslrvSKM4UIAyPHiljcs5mgbjBJyRf9k0NQsIRIGz-e9ICgYvZ4hjnURVoLY/pub?start=false&loop=false&delayms=3000'

revisited:
  <<: *default
  text: 'Collections Revisited'
  tags: ['inheritance']
  time: '21:06'
  save: '/files/Collections Revisited.pdf'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=065fa21b-4c31-49d0-9e75-afa5013a6790'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRc2JPUgSGi0Qv-WNE6tyFebba4xi10C1sr1TqlKXhF7CeNgciA15B4Rp1er0PU5ACwgUqzQYVO5nLU/pub?start=false&loop=false&delayms=3000'

nested:
  <<: *default
  tags: ['inheritance']
  text: 'Nested Classes'
  save: '/files/Nested Classes.pdf'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vQGU98zYWhimyRP15CrqUGU3tCGrbD_HZyrgoO7plH9Bip026Qt6lBfMB4upYTsbbbA9zsAfUy2_762/pub?start=false&loop=false&delayms=3000'

java:
  <<: *default
  text: 'Java Features'
  save: '/files/Java Features.pdf'
  time: '17:45'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=afafe125-83ba-4a06-9acd-afaf01584b44'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQyNW1eQU1VEzG4zkXLfWSzUMmeephSRac5SgxMPhYDrGHu4tSiRCZ8BC5Asr5cMiOArSOefQd296q-/pub?start=false&loop=false&delayms=3000'

lambdas:
  <<: *default
  tags: ['lambdas']
  text: 'Lambda Expressions'
  save: '/files/Lambda Expressions.pdf'
  time: '35:58'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=92c594f2-7825-4b47-99b8-afaf01584b69'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSfcsz5hcR8nM0AMwkn38IBfF51QQIGFv9B0z522Fz5QkOy_gZ4HNBvJiEU5Nre7ptzG0yCcUgwzAPQ/pub?start=false&loop=false&delayms=3000'

streams:
  <<: *default
  tags: ['streams']
  text: 'Stream Basics'
  save: '/files/Stream Basics.pdf'
  time: '17:36'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=75c5ed9b-3fc4-4b74-9154-afaf01584bd1'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTHslFp-CrVA0Lg2aKZoczqUpVvGQcfrmbi-wRp4_gEyqPOsuJ_haBi7JKIDi01Qyyrv4ft5a2KsXio/pub?start=false&loop=false&delayms=3000'

pipelines:
  <<: *default
  tags: ['streams']
  text: 'Stream Pipelines'
  save: '/files/Stream Pipelines.pdf'
  time: '20:37'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c5134ea0-52e1-467c-8d81-afaf01584c60'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSiGw5EXngr3WKMKWvcn0jnYpSP6AcaxT-eMIUNcywqIc-bLmUPvp1zwKlu5AvZ_m-k_z0wGRMG9zy4/pub?start=false&loop=false&delayms=3000'

assertions:
  <<: *default
  tags: ['debugging']
  text: 'Assertions'
  save: '/files/Assertions.pdf'
  time: '11:41'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fbd3d265-a920-4e12-8617-afbd011e56f2'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRP_rOtKQng1tAPlB5v02saggZvacdEZeZYfkX1F6catEEhpe3UGw4iiPmexovQhh6N4opD0NxyvsN_/pub?start=false&loop=false&delayms=3000'

logging:
  <<: *default
  tags: ['debugging']
  text: 'Logging'
  save: '/files/Logging.pdf'
  time: '24:00'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0fa38f02-d5b7-49b1-9645-afbd011e5726'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQJagxSE1XCK3rMcN_08iQdXO18CJyY2Mnww2_1bf1TbbioXf5g7jlq1PHZhX0CUJCJiTe724gRbcVZ/pub?start=false&loop=false&delayms=3000'

multithreading:
  <<: *default
  tags: ['threads']
  text: 'Multithreading'
  save: '/files/Multithreading.pdf'
  time: '13:35'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=856db121-0783-4dfd-b8b5-afca015f0304'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQg0FB_osCG1aL4vjPPp1HRMKTJm9_HIzs__izf7DaWkZ70ys4B14CPK1gyzZOBTvqCQJHHbqw4Ud41/pub?start=false&loop=false&delayms=3000'

lifecycle:
  <<: *default
  tags: ['threads']
  text: 'Thread Lifecycle'
  save: '/files/Thread Lifecycle.pdf'
  time: '15:40'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=2dd95a28-0250-42bb-9dae-afca015f03ab'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQycbWXlLYNVmOZaOHNQnuUZodavorlJEcsuJa69tOlfvSLQPpr39DcPvandPeQgKqOOg7TZuq_Ngi5/pub?start=false&loop=false&delayms=3000'

liveness:
  <<: *default
  tags: ['threads']
  text: 'Liveness'
  save: '/files/Liveness.pdf'
  time: '11:13'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ecfa716e-7e15-4ec0-8bfb-afca0169fd19'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTPdD96yklO8duuHgVDN81G_xP6xqQaRM8eaA2e75-s4uCZxAekRmkS2JijgDJ67kHkiovXQLd7HlXy/pub?start=false&loop=false&delayms=3000'

consistency:
  <<: *default
  tags: ['threads']
  text: 'Consistency'
  save: '/files/Consistency.pdf'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vSfpJpKez0wGz8A-ueNtIQXg8y3ptCTELGU8ES2_oeuAwt9295LRAq5ffWfwCScjmsrkLGnPhhTUxSe/pub?start=false&loop=false&delayms=3000'

synchronization:
  <<: *default
  tags: ['threads']
  text: 'Synchronization'
  save: '/files/Synchronization.pdf'
  time: '20:46'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b1c553a1-4ce7-4762-82f4-afca0166a784'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQHjH1aVQIbQKBXtLAMNHRa-qS2TZie-w8YYr9P4lXs_vcUcApAeLIxI0kSz2GF4CyADd8azxhbcdwE/pub?start=false&loop=false&delayms=3000'

coordination:
  <<: *default
  tags: ['threads']
  text: 'Coordination'
  save: '/files/Coordination.pdf'
  time: '14:46'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=41f8f064-f109-4e6d-b62b-afcd0138d2e5'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQkX8lY88RA_BDHWz4nM9JoVuB4fLvXmxOKKv6LWvXIA8Xgq17dE6y2V4dZhc4D3csyszbDbECz5ntC/pub?start=false&loop=false&delayms=3000'

locks:
  <<: *default
  tags: ['threads']
  text: 'Conditional Locks'
  save: '/files/Conditional Locks.pdf'
  time: '12:49'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=e47edbae-5fc3-4d2a-bec4-afca0169fa70'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTo6KJSvdr_PWmaunL6LkyTdzMsgWnjQU_VfqWOGEPaG2XfYvpkgJWvbDhbhzYgO-dnR8nmbp9wSPRz/pub?start=false&loop=false&delayms=3000'

volatile:
  <<: *default
  tags: ['threads']
  text: 'Volatile Keyword'
  save: '/files/Volatile Keyword.pdf'
  time: '10:31'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ee504e4e-65e6-494f-b64a-afca0169fc11'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQf8Exzc0l1hR4rA2932_MzScdml8OA1fYIdWgW5yOXPHtZIRY7S9B-koCzUI7HEe6MdBLfJXY6bQZf/pub?start=false&loop=false&delayms=3000'

pools:
  <<: *default
  tags: ['threads']
  text: 'Thread Pools and Work Queues'
  save: '/files/Thread Pools and Work Queues.pdf'
  time: '10:02'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9e729af8-d9f0-4537-92da-afca0169fbb0'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vS19DIgUp8W95_ChgGpM7ve2ItWmaWY6YFP8tyE-k3gA3tQ9cbj0vd6ZmP-gCi7fXhFaQdoh6BWU_0f/pub?start=false&loop=false&delayms=3000'

regex:
  <<: *default
  tags: ['regexes']
  text: 'Regular Expressions'
  save: '/files/Regular Expressions.pdf'
  time: '14:08'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=efcf18e0-1fc0-4595-96da-afd80183d261'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSLVGeiqwzi3b8xtD0ZpnEsKDJl9M7kO2BI0GsszcHChNEhUtx6AJgeRopxBHIeJ-Bn4soKUrtZZicw/pub?start=false&loop=false&delayms=3000'

web:
  <<: *default
  tags: ['web']
  text: 'Web Basics'
  save: '/files/Web Basics.pdf'
  time: '06:34'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8e402979-8beb-4dc9-a82f-afd801860e7e'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQyx-0sbMzXbqWjoKW9fEIoLMgvO42cIT4m04nxRx1LYK7F_0nNjN4Vy1jptzaQFlWazEXL97UBkgex/pub?start=false&loop=false&delayms=3000'

url:
  <<: *default
  tags: ['web']
  text: 'Uniform Resource Locator (URL)'
  save: '/files/Uniform Resource Locator (URL).pdf'
  time: '14:51'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=1c4fa5b2-33a5-42ac-9dee-afd90032ff16'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSho31BZkNLMgEujPcWbKmqNG2ZY9hhYvZOgsqGdE52vTD_VRKos10FLVkcNV3v1Y1SFPlkSbkNAwn8/pub?start=false&loop=false&delayms=3000'

html:
  <<: *default
  tags: ['web']
  text: 'Hypertext Markup Language (HTML)'
  time: '21:03'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fe207fce-2c91-4de6-b71b-afd801860e9d'

http_intro:
  <<: *default
  tags: ['web']
  text: 'Hypertext Transfer Protocol (HTTP)'
  save: '/files/Hypertext Transfer Protocol (HTTP).pdf'
  time: '07:37'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=86cdb762-93f5-49ae-b2ba-afd90162eabd'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRFNQNP4jwQk9p7BrrPkTKiUMOJteNJ99MPodgafcvGoYib8s_T83PuSRyOEs2WE8EhB8nNAXR1op91/pub?start=false&loop=false&delayms=3000'

http_demo:
  <<: *default
  tags: ['web']
  text: 'HTTP Demos'
  save: '/files/Hypertext Transfer Protocol (HTTP).pdf'
  time: '11:59'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=b91f50d7-d002-47c3-a290-afd90162eae1'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRFNQNP4jwQk9p7BrrPkTKiUMOJteNJ99MPodgafcvGoYib8s_T83PuSRyOEs2WE8EhB8nNAXR1op91/pub?start=false&loop=false&delayms=3000'

dynamic:
  <<: *default
  tags: ['web']
  text: 'Static vs Dynamic Web'
  save: '/files/Static vs Dynamic Web.pdf'
  time: '08:29'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vR-HXvkl7cVq4YHBw9XBuSDcLlGFTvBlzfe8-SAaqIgVY4Az2my-vcBz426YTGm8vZcJeWHMqkitxGi/pub?start=false&loop=false&delayms=3000'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=73283792-33d2-4001-af0f-afdc0027768c'

jetty:
  <<: *default
  tags: ['servlets']
  text: 'Jetty and Servlets'
  save: '/files/Jetty and Servlets.pdf'
  time: '10:19'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vT_fIyB-Wdl0QwpHf5KDpfzUrk6B_XkGsmp68sjL1Fu7ua3yZiTKXwVGQaP5LL9eLNxkjHL7NmC1cQH/pub?start=false&loop=false&delayms=3000'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=73887688-db72-4e76-be0e-afdc002776d6'

relational:
  <<: *default
  tags: ['sql']
  text: 'Relational Databases'
  save: '/files/Relational Databases.pdf'
  time: '19:12'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=753c00bf-903a-4c4e-9e39-afef003fbb2c'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQ0KFxmtZiY2FvNPf5BaYVwotg9BiebdRhN5mmHxltmy0Y_vXCTlm1Hxq8-Cl7VCH74XUghBbkTgAFR/pub?start=false&loop=false&delayms=3000'

sql:
  <<: *default
  tags: ['sql']
  text: 'Structured Query Language (SQL)'
  time: '20:45'
  save: '/files/Structured Query Language (SQL).pdf'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4c557e02-4323-47fc-add5-afef003fbb64'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTxHpIGuQPb7mBLga9sDgcOOJmX2OhBrYEN_kSPKJzHpV0kxxXXh0s7g_GSsjb6ZvLx-cx0qC3V6mgK/pub?start=false&loop=false&delayms=3000'

jdbc:
  <<: *default
  text: 'Java Database Connectivity (JDBC)'
  save: '/files/Java Database Connectivity (JDBC).pdf'
  time: '12:12'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTVzPbBtOzPowhYoshT3YdbHIzlTKHzfZxzOMJUziA3tXdMpVO2pyCGvcv_SJSjlfU0N4fSaoXNjIM6/pub?start=false&loop=false&delayms=3000'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=0b85317c-d4ce-4823-bed2-aff00152f1dd'
  tags: ['jdbc']

testing_bugs:
  <<: *default
  tags: ['testing']
  text: 'Software Bugs'
  save: '/files/Software Bugs.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQdjUj1o8oAntzst1ZMz7jWIDWkZo6pxVhVW7yV3BkR4SMcBVXqfA5kU2uXyTPOUGN0Y_KKKH2b3RsO/pub?start=false&loop=false&delayms=3000'

testing_intro:
  <<: *default
  tags: ['testing']
  text: 'Software Testing'
  save: '/files/Software Testing.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSsb_Oz18l8oBxTcOM846kBLhBcc8MqoC_SBPQ9T162lnAw44mJmo5aQOm6fhg8XLrR_jMvix_7XT29/pub?start=false&loop=false&delayms=3000'

testing_unit:
  <<: *default
  tags: ['testing']
  text: 'Unit Testing'
  save: '/files/Unit Testing.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQqlccD49DFn6ShL-ImZ7H34QaUj-loGq4F4YlBBrbwSFbcdLm1YivUCu7TmObJPkj7V_TkZvdYu6RK/pub?start=false&loop=false&delayms=3000'

# recap:
#   <<: *default
#   text: 'Course Recap'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRWVK3jB5Ec0QJYLNd__v-6oz9FvnOMqTXGTCBPk0dE0k6bsqtqoEUIHXaUWwqKlkIuAshjf8IcXOdF/pub?start=false&loop=false&delayms=3000'
