defaults: &default
  text: 'Pending'
  icon: 'slides'
  tags: []
  # href: 'video link'
  # view: 'slide link'
  # time: '00:00'
  # save: '/files/????.pdf'

course_intro:
  <<: *default
  text: 'Course Introduction'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vS8sACyf9lrjGUTkS3TxSuq0v6As8POig4tSvkYseWYTaHtpYb9JEaFz8CWI6M2hNVJB8kEUQHHMaW5/pub?start=false&loop=false&delayms=3000'
  save: '/files/Course Introduction.pdf'

projects:
  <<: *default
  text: 'Project Overview'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vS6DlWNE2SBOL_7TRoKEsIq9LwLhZXJvkTAxkO5drcCfSA80pnWt_jnOEQ3-nVqLW-L-S179iykHOj9/pub?start=false&loop=false&delayms=3000'
  save: '/files/Project Overview.pdf'

exceptions:
  <<: *default
  text: 'Exception Handling'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=fc1367c9-aa48-4e6d-82bf-afaf015097f9'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRMqQrt0IaiwZL5Du1KcQIONLkNXtnS6VR2FnRXBn1c84dMSleUuH6jl0OJNLtSMS_WujxCSow9UXcI/pub?start=false&loop=false&delayms=3000'
  save: '/files/Exception Handling.pdf'
  time: '10:25'
  tags: ['exceptions']

paths:
  <<: *default
  text: 'Paths and Files'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=825bbf06-997d-438e-b712-afaf015099a0'
  time: '20:29'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRjEUU0FIhBZIeMeU9O5L3Fc9WFAb9RvjA3dNANUjxupwWPH6Uw86tYEczVtrbfDzLFLub3je-pwGsg/pub?start=false&loop=false&delayms=3000'
  save: '/files/Paths and Files.pdf'
  tags: ['files']

data:
  <<: *default
  tags: ['data']
  text: 'Abstract Data Types'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d4aa37cf-3337-4b1e-bd70-afaf015097d3'
  time: '12:25'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTkWFYYWCAs5DHir-jf68Yd5BWa_u8ymf7Ez-gqRaAhgmzEbyI0WoThN9tWPoa7EzgrkJDyaI65vZL3/pub?start=false&loop=false&delayms=3000'
  save: '/files/Abstract Data Types.pdf'

framework:
  <<: *default
  tags: ['data']
  text: 'Collections Framework'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=982b0640-d13b-48ce-8493-afaf01509713'
  time: '20:26'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQ3tDfuttbeApPhgaOhsyxjHrUeIMub206X9HWbs2cORCCGD1b2o05jDBhtNPeK_GxuhsfSLM_RcLDT/pub?start=false&loop=false&delayms=3000'
  save: '/files/Collections Framework.pdf'

help:
  <<: *default
  tags: ['none']
  text: 'Getting Help'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vSxGLWZBMDIPj7uV_8tB7Y2l9cgAoygX5dO9ip5vD3d_MdoSepNW7x2rRg7rmuR6G2O1eKCnVQrb6Xs/pub?start=false&loop=false&delayms=3000'
  save: '/files/Getting Help.pdf'

oop:
  <<: *default
  tags: ['objects']
  text: 'Object Oriented Programming'
  time: '25:22'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=47838700-2052-4e68-b6f7-afa2012c87e3'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQkzEnVG9sFgjElR-K2xUi91wYtj3bC82mWk8XhaRaz3ihMJNqQbciSKSkAxJAw_UQW7TGo-Cevsp05/pub?start=false&loop=false&delayms=3000'
  save: '/files/Object Oriented Programming.pdf'

generics:
  <<: *default
  tags: ['inheritance']
  text: 'Generic Types'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8f3be91f-6e33-4838-ae40-afa5012f761c'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRczaRucL8_HpFU1hH8WY7TQr2XSplEUY78sBK9t-hTCIkDK9kDvAuVne569IHct2tDNG9724VeE92g/pub?start=false&loop=false&delayms=3000'
  save: '/files/Generic Types.pdf'
  time: '16:53'

inheritance:
  <<: *default
  tags: ['inheritance']
  text: 'Inheritance Relationships'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8dafbf27-1c7d-4a7c-aa2f-afa5013a6828'
  time: '15:09'
  save: '/files/Inheritance Relationships.pdf'

abstract:
  <<: *default
  tags: ['inheritance']
  text: 'Abstract and Interfaces'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=217a9f63-2bcd-4869-b79c-afa5013a66f5'
  time: '14:36'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRARVHCO1k8XhC-yjANvl89WX91qKPJ9e3f2Em8ITBihWDf0Xym01x38Bz8DdigBFHHMfrgtuwgCFGE/pub?start=false&loop=false&delayms=3000'
  save: '/files/Abstract and Interfaces.pdf'

final:
  <<: *default
  tags: ['inheritance']
  text: 'Final Keyword'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4e843b8f-0703-4199-ba76-afa5013a67b1'
  time: '10:06'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQ1ZQfSwdQPikCJFXVf5YbWHAMh95r84nAr5Ply5DeYYY0OqU0EqJA0wsSFiX49Eh9qjyZhsFkGNZzs/pub?start=false&loop=false&delayms=3000'
  save: '/files/Final Keyword.pdf'

casting:
  <<: *default
  tags: ['inheritance']
  text: 'Casting'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=4eab4121-1dad-40c5-a5a1-afa5013a671f'
  time: '10:42'
  save: '/files/Casting.pdf'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQKZWkx3KuWfriEUZx8n3VWwWJwqq1MyiMoJwWqXPQ-B8HdsaaOZgMPQ3cwDhuBcahLrDz3jtNKoeH-/pub?start=false&loop=false&delayms=3000'

object:
  <<: *default
  tags: ['inheritance', 'objects']
  text: 'Object Class'
  time: '06:59'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8c2e483d-a4a3-4691-b8b1-afa201317dd4'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQgaY1m74u6_3ra6dibqslrvSKM4UIAyPHiljcs5mgbjBJyRf9k0NQsIRIGz-e9ICgYvZ4hjnURVoLY/pub?start=false&loop=false&delayms=3000'

revisited:
  <<: *default
  text: 'Collections Revisited'
  tags: ['inheritance']
  time: '21:06'
  save: '/files/Collections Revisited.pdf'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=065fa21b-4c31-49d0-9e75-afa5013a6790'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vRc2JPUgSGi0Qv-WNE6tyFebba4xi10C1sr1TqlKXhF7CeNgciA15B4Rp1er0PU5ACwgUqzQYVO5nLU/pub?start=false&loop=false&delayms=3000'

nested:
  <<: *default
  tags: ['inheritance']
  text: 'Nested Classes'
  save: '/files/Nested Classes.pdf'
  href: 'https://docs.google.com/presentation/d/e/2PACX-1vQGU98zYWhimyRP15CrqUGU3tCGrbD_HZyrgoO7plH9Bip026Qt6lBfMB4upYTsbbbA9zsAfUy2_762/pub?start=false&loop=false&delayms=3000'

java:
  <<: *default
  text: 'Java Features'
  save: '/files/Java Features.pdf'
  time: '17:45'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=afafe125-83ba-4a06-9acd-afaf01584b44'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vQyNW1eQU1VEzG4zkXLfWSzUMmeephSRac5SgxMPhYDrGHu4tSiRCZ8BC5Asr5cMiOArSOefQd296q-/pub?start=false&loop=false&delayms=3000'

lambdas:
  <<: *default
  tags: ['lambdas']
  text: 'Lambda Expressions'
  save: '/files/Lambda Expressions.pdf'
  time: '35:58'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=92c594f2-7825-4b47-99b8-afaf01584b69'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSfcsz5hcR8nM0AMwkn38IBfF51QQIGFv9B0z522Fz5QkOy_gZ4HNBvJiEU5Nre7ptzG0yCcUgwzAPQ/pub?start=false&loop=false&delayms=3000'

streams:
  <<: *default
  tags: ['streams']
  text: 'Stream Basics'
  save: '/files/Stream Basics.pdf'
  time: '17:36'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=75c5ed9b-3fc4-4b74-9154-afaf01584bd1'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vTHslFp-CrVA0Lg2aKZoczqUpVvGQcfrmbi-wRp4_gEyqPOsuJ_haBi7JKIDi01Qyyrv4ft5a2KsXio/pub?start=false&loop=false&delayms=3000'

pipelines:
  <<: *default
  tags: ['streams']
  text: 'Stream Pipelines'
  save: '/files/Stream Pipelines.pdf'
  time: '20:37'
  href: 'https://usfca.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c5134ea0-52e1-467c-8d81-afaf01584c60'
  view: 'https://docs.google.com/presentation/d/e/2PACX-1vSiGw5EXngr3WKMKWvcn0jnYpSP6AcaxT-eMIUNcywqIc-bLmUPvp1zwKlu5AvZ_m-k_z0wGRMG9zy4/pub?start=false&loop=false&delayms=3000'

# regex:
#   <<: *default
#   tags: ['regexes']
#   text: 'Regular Expressions'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vTO88-l6I37jTV3eM1QGEPbsZ9XsYM5YCascMfUqjzYPXSQnJG1elC0Hx0oUw9MT9z781i8ApW3nYmh/pub?start=false&loop=false&delayms=3000'

# testing_bugs:
#   <<: *default
#   tags: ['testing']
#   text: 'Software Bugs'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRx3Celd7paeP5-TbE-LEU-1f1UzcoG93-PlqwrmTsW76tMXlyOH3qxlJB067TaeUWEznDGa7CsDcwN/pub?start=false&loop=false&delayms=3000'

# testing_intro:
#   <<: *default
#   tags: ['testing']
#   text: 'Software Testing'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vSBCRFRsHERFo9gqwW8TsusCW63wgsBDXs5k2SBuphtbigsZplHkiQB6sxesTaNFcKPHDU8u2f7ZpbD/pub?start=false&loop=false&delayms=3000'

# testing_unit:
#   <<: *default
#   tags: ['testing']
#   text: 'Unit Testing'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRRfeHE_j03Wl4zQRnubmZBztMMC94gUt4Gs2FnN7Ka31KuO7GMK8bQjmEzSHnoZZeqrnRQNCAZTDNU/pub?start=false&loop=false&delayms=3000'

# assertions:
#   <<: *default
#   tags: ['debugging']
#   text: 'Assertions'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRLXyc0T98b27UmaNg-jZONLb-CIRy_TFAL5sGendDFbFFc2MmV6ZOURlEwZhE6WBDr8Q36Degsx9vA/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1mSAPW69YHYzl-Uqz-FyZY3Eg8j7StxiP/view?usp=sharing'

# logging:
#   <<: *default
#   tags: ['debugging']
#   text: 'Logging'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vSW62BhOpFZQzghSV5fkrmZCGQ3udhK-myxFmh9Cf1WfsiP6PK0h4PFx02DUhidksERTk1Ou4_QQ8nh/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1ZJnvRK56Zj43E8pkby_YVPfQm7rwM_PT/view?usp=sharing'

# multithreading:
#   <<: *default
#   tags: ['threads']
#   text: 'Multithreading'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRX6RCeUBV4oY2pE3PwPR11oV0CbXnJYDQg6fupgT6b1w44qmzsCsRfWyhd_kIdZjtqECwITRfm-X-L/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1bDx_QfV8uXgxBnMuGW1BifaOkcHuVsxU/view?usp=sharing'

# lifecycle:
#   <<: *default
#   tags: ['threads']
#   text: 'Thread Lifecycle'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vSR1cZ0OOKgBSz2MkWKaWzBZJPsm33joCC9fX9zAmh23bhs6lPuO11TCPOs3gJzk2WvN92Uw69K7j1m/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/19WIE-aE_n2okfI-Evk7OMEtCUvzaCSwT/view?usp=sharing'

# consistency:
#   <<: *default
#   tags: ['threads']
#   text: 'Consistency'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vTRAzhLDNE32VRqGC3dddI0pFxqiN_8DOihGJv6OuVj-3oiJEgBSGJQMIZBD0WwL5vMpfKuu95Q-tTa/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1XGxlAjAP10M77GLTy7mRquS6Miy9PTkh/view?usp=sharing'

# liveness:
#   <<: *default
#   tags: ['threads']
#   text: 'Liveness'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vS6RCZPY_h5NtvogQccLSEfTCAXz-Hqfmxgqkolqp6Cc41gCc8WWcb-aMXADAFvKwQ9HeKKjfjw6PmL/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1ZoPqrdm4e2exLo9djFJcoLKBRwNMOEII/view?usp=sharing'

# synchronization:
#   <<: *default
#   tags: ['threads']
#   text: 'Synchronization'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vQTud-UE2KhToUmELC4yO3Fp9VI_0YorUE0aMckdmrLN8K8-bemUSsVg5kHuCOGihsYoTkbsfVci3FN/pub?start=false&loop=false&delayms=3000'

# locks:
#   <<: *default
#   tags: ['threads']
#   text: 'Conditional Locks'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vQ141tZGTlSrULwdwSfhjaNU4N_c7VpfNNXE-3n2oLKF2nGzif3LZeQOgNNFJAj8iipx6bi2v10qvDE/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1M9bd401kt3RkjjcFw8jI92hMbhW4CtQP/view?usp=sharing'

# coordination:
#   <<: *default
#   tags: ['threads']
#   text: 'Coordination'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vTMD7lRdye-5kptn3d68vQYzJq2OQpIKtGLHyPK_sPYRExA5DWv9arIsF0121CP8PO2lV5UkJA-dhlb/pub?start=false&loop=false&delayms=3000'

# volatile:
#   <<: *default
#   tags: ['threads']
#   text: 'Volatile Keyword'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRnhd4UbzvMq5UjxONPTslBI4gXqR-iwhlk3Uo8y3SGb1YOipeB4wBK-IVuwrI7rrp_jGtg1beYqeup/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1PtN8QKiJurwN1aIi0bruYMNnA7aJgnC8/view?usp=sharing'

# pools:
#   <<: *default
#   tags: ['threads']
#   text: 'Thread Pools and Work Queues'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vSj0ekNLfD_w7tAqlBzOYHlwAF4m_5_PD6j_t47xT7-0qUz1lG9nvllKiDgcGBr-kTDBLy5jLSwgOFS/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1Nz47N4dqlnypm3HSvtOB0iMwmO35aMgR/view?usp=sharing'

# web:
#   <<: *default
#   tags: ['web']
#   text: 'Web Basics'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vR6qw7FOZ64KTgnn9HNMFcZxxbDJFNOywOj9eHIhK4MK5cEcmkNYp2xd7kK0iPygYLLlpwz2iaBm3tC/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1EjtB-Ikl7fpijJ9k5B1I0aSRc74g3pXQ/view?usp=sharing'

# url:
#   <<: *default
#   tags: ['web']
#   text: 'Uniform Resource Locator (URL)'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vTMMCl3TqZwp_1PiKZuBoaPYhnFTv_4jS3PddLBB11Tr3iQYs_jAKzdzNqeSuK7KDwXrS7nqR2VZNf0/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1RmbX1-3Qqm5OyQJVZe8ugtqRUiO8THX-/view?usp=sharing'

# http:
#   <<: *default
#   tags: ['web']
#   text: 'Hypertext Transfer Protocol (HTTP)'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vSEzRZio0k4FRdSRlxeauT0i_D54JWhi6ZcEEaYFBJcXFu7o7SL81zhwsot_jxAWCeCOolg8sQsr13K/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1L-JTuRZKalismoydzJUaSe2szdobX-L1/view?usp=sharing'

# dynamic:
#   <<: *default
#   tags: ['web']
#   text: 'Static vs Dynamic Web'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vT73FZwlsGn2UvuXfv37r6iokph2P2k7ZRn6qMB97UevKkttkrs-RaKn4Og-ndwjC0cLRcU1PyN4Q94/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1ix3i4i2eoHy-D9aTYgEkp9IPBBzgYxRw/view?usp=sharing'

# jetty:
#   <<: *default
#   tags: ['servlets']
#   text: 'Jetty and Servlets'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vT39ddllMZONA2_tbfEttwCvKAtUdKy5wiGZi9DM-3mCz7yL624y2SEEPsjHYFkQfLLsb4vUcv4FWhO/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1OtvslLGJB1FOhoQRYv1yTFMLE6OCQCCN/view?usp=sharing'

# relational:
#   <<: *default
#   tags: ['sql']
#   text: 'Relational Databases'
#   save: true
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vS6PhZvk930AAO0SHo7uXY4c-gfAv3-xUFiEDPKqI1MIOptUkBXtj1BfAYVZyi5vv72f8g1qdzg6Wxr/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1L-CLDjzNTGVzZPds1CkaU9uGvHl7FtwW/view?usp=sharing'

# sql:
#   <<: *default
#   tags: ['sql']
#   text: 'Structured Query Language (SQL)'
#   tube: 'https://drive.google.com/file/d/1jjVGe-4dbyefIr3k_5z2ZEjXL5cPL3MH/view?usp=sharing'
#   save: true
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vREjA4w_CDftw9Gcl6Uwsxb2YxPckK9r7_3GoxYLbSbJF0aNbXPyVaJGAjz6JEFYRiciIL0nH9Hc9to/pub?start=false&loop=false&delayms=3000'

# dbaccounts:
#   icon: 'website'
#   save: false
#   text: 'Database Accounts'
#   href: '/guides/sql/database-accounts.html'

# sqlintro1:
#   icon: 'website'
#   save: false
#   text: 'SQL Intro, Part 1'
#   href: '/guides/sql/sql-intro-started.html'
#   tube: 'https://drive.google.com/file/d/1W5pneWmLOXVkDrvxL9YWhRsZ8PwjM4vZ/view?usp=sharing'
#   tags: ['sql']

# sqlintro2:
#   icon: 'website'
#   save: false
#   text: 'SQL Intro, Part 2'
#   href: '/guides/sql/sql-intro-joining.html'
#   tube: 'https://drive.google.com/file/d/1auHLPbiHxJq8tr_78HtNrKELu2Wi_zk4/view?usp=sharing'
#   tags: ['sql']

# sqlintro3:
#   icon: 'website'
#   save: false
#   text: 'SQL Intro, Part 3'
#   href: '/guides/sql/sql-intro-enforcing.html'
#   tube: 'https://drive.google.com/file/d/1MOokzFUB8FXT2msoxU65PcqMlxYOsd0B/view?usp=sharing'
#   tags: ['sql']

# sqldemo:
#   icon: 'website'
#   save: false
#   text: 'SQL Faculty Demo'
#   href: '/guides/sql/sql-demo-intro.html'
#   tags: ['sql']

# jdbc:
#   <<: *default
#   text: 'Java Database Connectivity (JDBC)'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vQSTQGh8TMFe3Jn8oShnlC3mnWcyAixqbc9bZ-417tqPcvay0WFRactomEqoQLW-x2RHcA_8iSVHf2O/pub?start=false&loop=false&delayms=3000'
#   tube: 'https://drive.google.com/file/d/1bgEAcSx7OhRRziOo8MsiP_DjcrOrhClG/view?usp=sharing'
#   tags: ['jdbc']

# recap:
#   <<: *default
#   text: 'Course Recap'
#   href: 'https://docs.google.com/presentation/d/e/2PACX-1vRWVK3jB5Ec0QJYLNd__v-6oz9FvnOMqTXGTCBPk0dE0k6bsqtqoEUIHXaUWwqKlkIuAshjf8IcXOdF/pub?start=false&loop=false&delayms=3000'
